### ISSUE TITLE
Question regarding Languages Aligning 

### ISSUE THREAD

**Issue by AlexKLMan** [julbean/describealign#11]
Thank you for telling me about your amazing program on Discord! I’m building up my Jellyfin library, and this is super useful.
I saw in the documentation that dub alignment is a feature and was wondering if I need to enable it before trying it out? I just tested Harry Potter in English (non-audio described) with Cantonese, but the audio wasn’t in sync.
I’m not sure if I’m doing something wrong or if I’ve forgotten to enable a setting.
Thanks again!

**Comment by julbean** [comment]
The default settings are able to align dubbed media just the same as described media.  You shouldn't need to adjust anything.  You can check the alignment_plots folder for a graph (as well as a text version) which has information about the alignment.  That might help you figure out what's going wrong for the particular files you're working with.

**Comment by julbean** [comment]
Also, if you enable the stretch_audio setting, that will keep the original audio track that came with the video alongside the stretched and aligned audio track, so you can switch between them in your media player to check the alignment that way.  In VLC, the hotkey to swap between audio tracks is b.
