### ISSUE TITLE
When trying to losslessly edit videos with a shorter mp3 audio, the video's duration doesn't get cut

### ISSUE THREAD

**Issue by sukiletxe** [julbean/describealign#9]
Although the video and the audio get correctly aligned, silence is inserted between audio segments, effectively keeping the video's duration unchanged. Interestingly, it seems that the alignment plots (the text version, at least) are similar.

**Comment by julbean** [comment]
That's odd, with default settings the audio is directly copied, so it can't be the script adding silence.  I suppose your video player could be preventing the video from fast-forwarding properly and adds the silence instead?  What player are you using?  VLC works fine for me.  With the --stretch_audio option, gaps in the audio description appear to be correctly replaced with original audio on my system as well.
Are you referring to the default settings not cutting off the end of the video if the audio description ends before it?  That's intended behavior, but if you'd like to share reasoning for some other desired behavior, I'm open to suggestions!

**Comment by sukiletxe** [comment]
OK, it could indeed be the latter. Probably I saw the duration and concluded the silence was inserted instead. I can't recall if I'm trying with the original mp3 which gave me problems, but I can see that indeed there is no silence inserted. Maybe I navigated too far to the right before, effectively landing in a part where there was no more audio. 

Interestingly, mp3 and aac (or my files, at least) seem to work differently, as combining mp4 with mp3 doesn't cut the video duration (if I start with a 5 minute video, after cutting it will still last 5 minutes, with silence at the end), but combining mp4 and aac does.

So sorry for the dumb confusion. If you don't want to investigate this last point, feel free to close this.

**Comment by julbean** [comment]
Interesting, I'm not able to reproduce what you're seeing with aac files.  Do you get this behavior when you convert an mp3 into an aac using ffmpeg?

**Comment by sukiletxe** [comment]
Sorry, not aac, flac. I need some sleep 🤣.

**Comment by julbean** [comment]
Wasn't able to reproduce, as combining a flac with an mp4 was actually just crashing for me!  Apparently flac codecs are only experimentally supported in this version of ffmpeg, so I fixed that in https://github.com/julbean/describealign/commit/ff8035da4abe5ab585340e9ad28302b0cfe0b106.  Doesn't cut off the video for me now that it's working; does this new latest version on the github work for you?

**Comment by sukiletxe** [comment]
Yup, it does, it makes the file last 4 minutes (the original's duration) instead of 2 (the cut's duration).

(Interestingly, I had to use the GUI for some reason, as the CLI version "lost stdin". Oh well).

**Comment by julbean** [comment]
Are you using the binary or the .py file?  The .py should have the CLI working, while the latest binaries have bugged CLIs.  I haven't updated the binaries or the pip versions with the fix, by the way

**Comment by sukiletxe** [comment]
The binary. I didn't know how to install from source from gitHub.

**Comment by julbean** [comment]
You just download the python script and run it like "python describealign.py video.mp4 audio.flac"

**Comment by sukiletxe** [comment]
OK, thanks! Now I tried aligning with both flac and mp3, and I got the same duration with both of them.
